name: 🐛 Bug Report
description: Report a bug or unexpected behavior in AI File Sorter
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a bug! 
        
        Please fill out this form to help us understand and fix the issue quickly.
        
        **For Copilot Users:** If you have a `COPILOT_ERROR_*.md` file from the app, paste its contents in the "Additional Context" section at the bottom.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I am using the latest version of AI File Sorter
          required: false
        - label: I have read the README and troubleshooting documentation
          required: false

  - type: dropdown
    id: bug-category
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - Application Crash/Won't Start
        - DLL/Library Loading Error
        - Qt/UI Issue
        - Categorization/AI Model Issue
        - File Sorting/Moving Error
        - Database/Cache Issue
        - API Integration (OpenAI/Gemini)
        - Installation/Build Issue
        - Performance/Slow Operation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application unusable
        - High - Major functionality broken
        - Medium - Some functionality affected
        - Low - Minor inconvenience
        - Cosmetic - Visual/UI issue only
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Example: Application crashes immediately after clicking 'Analyze' button with error message about QTableView::dropEvent"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Launch AI File Sorter
        2. Select directory 'C:\Downloads'
        3. Click 'Analyze' button
        4. Application crashes with error dialog
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The application should analyze the files and show the categorization dialog"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Application crashes with 'Critical DLL Setup Error' dialog"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Windows 11
        - Windows 10
        - Windows (Other)
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch/Manjaro)
        - Linux (Other)
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS (Older)
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: AI File Sorter Version
      description: What version are you using? (Check Help → About or README.md)
      placeholder: "e.g., 1.5.0"
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: How did you install AI File Sorter?
      options:
        - Downloaded release binary
        - Built from source
        - Package manager (apt/dnf/brew)
        - Other
    validations:
      required: true

  - type: dropdown
    id: llm-type
    attributes:
      label: LLM Type Used
      description: Which LLM were you using when the bug occurred?
      options:
        - Local LLM (LLaMa/Mistral)
        - OpenAI API (ChatGPT)
        - Google Gemini API
        - Not applicable to this bug
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error Messages
      description: Copy any error messages, dialog text, or console output here
      placeholder: |
        Error: Critical DLL Setup Error
        Details: Could not locate QTableView::dropEvent in Qt6Widgets.dll
        
        See log file: C:\Users\...\AppData\Roaming\aifilesorter\logs\errors.log
      render: shell
    validations:
      required: false

  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: |
        Please attach or paste relevant log files:
        - Windows: %APPDATA%\aifilesorter\logs\errors.log
        - Linux: ~/.cache/aifilesorter/logs/errors.log
        - macOS: ~/Library/Application Support/aifilesorter/logs/errors.log
        
        **For large files:** Upload as attachment rather than pasting
      placeholder: Paste log contents here or note "See attached files"
      render: shell
    validations:
      required: false

  - type: textarea
    id: copilot-error-file
    attributes:
      label: Copilot Error File (if available)
      description: |
        If you have a COPILOT_ERROR_*.md file (found in same logs directory), paste its contents here.
        This file contains detailed context that helps diagnose the issue.
      placeholder: Paste COPILOT_ERROR_*.md contents here
      render: markdown
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: |
        Additional system details (if known):
        - GPU: NVIDIA RTX 3080, AMD Radeon, etc.
        - Qt Version: Check error logs or about dialog
        - CUDA Version: Run `nvidia-smi` if applicable
        - Vulkan Support: Run `vulkaninfo` if applicable
      placeholder: |
        GPU: NVIDIA RTX 3080
        Qt Version: 6.5.3 (compiled), 6.7.0 (runtime) ← Mismatch!
        CUDA: 12.2
      render: shell
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if found)
      description: Have you found any temporary workaround for this issue?
      placeholder: "Launching with --vulkan=off flag allows application to start, but performance is reduced"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context, screenshots, or information that might help diagnose the issue.
        
        **Screenshots:** Drag and drop images here
        **Files:** Attach relevant files
        **Environment:** Special configurations, antivirus, security software, etc.
      placeholder: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: ai-analysis
    attributes:
      label: AI Assistant Analysis Request
      description: Optional - Request automated analysis
      options:
        - label: Please have an AI assistant analyze this issue and suggest potential fixes
          required: false
        - label: This issue may be related to previous bugs (check for patterns)
          required: false
