name: ✨ Feature Request
description: Suggest a new feature or enhancement for AI File Sorter
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature! 
        
        Please describe your idea clearly so we can evaluate and potentially implement it.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature doesn't already exist in the latest version
          required: true
        - label: I have checked FUTURE_IMPROVEMENTS.md for planned features
          required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - File Organization/Categorization
        - AI/LLM Functionality
        - User Interface/UX
        - Performance Optimization
        - Error Handling/Reporting
        - API Integration
        - Database/Caching
        - Security/Privacy
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the app
        - High - Would significantly improve my workflow
        - Medium - Nice to have enhancement
        - Low - Small improvement
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: |
        Currently, when I have 10,000+ files to categorize, the app becomes slow and unresponsive.
        I need a way to process files in batches to avoid memory issues.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution in detail
      placeholder: |
        Add a "Batch Size" setting that allows users to:
        1. Set a maximum number of files to process at once (default: 500)
        2. Automatically split large directories into batches
        3. Show progress across batches (e.g., "Batch 2 of 15")
        4. Allow pausing/resuming between batches
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        Alternative 1: Manually select subsets of files (cumbersome for large directories)
        Alternative 2: Split directory into folders first (requires manual work)
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Use Case 1: Organizing 50,000 photos from multiple cameras
        Use Case 2: Cleaning up a Downloads folder with 5+ years of accumulated files
        Use Case 3: Processing entire external hard drives (500GB+ of files)
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: UI Mockup or Wireframe
      description: |
        If this involves UI changes, provide a mockup, sketch, or description
        You can drag and drop images here
      placeholder: Describe the UI or attach a mockup image
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Implementation Ideas
      description: |
        If you have technical knowledge, suggest implementation approaches
        (Optional - developers will handle implementation)
      placeholder: |
        Could use a queue-based system where:
        - FileScanner adds files to a bounded queue (max 500)
        - Categorization processes queue in chunks
        - ProgressTracker monitors batch completion
    validations:
      required: false

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes to existing functionality?
      options:
        - "No - Purely additive feature"
        - "Minor - Small changes to existing behavior"
        - "Yes - Significant changes required"
        - "Not sure"
    validations:
      required: false

  - type: textarea
    id: similar-features
    attributes:
      label: Similar Features in Other Apps
      description: Have you seen similar features in other applications?
      placeholder: |
        Adobe Lightroom has batch processing with:
        - Configurable batch sizes
        - Background processing option
        - Ability to continue working while processing
    validations:
      required: false

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Contribution Interest
      description: Would you be willing to help implement this feature?
      options:
        - "Yes - I can code and would like to contribute"
        - "Yes - I can help with testing"
        - "Yes - I can help with documentation"
        - "Maybe - Depends on complexity"
        - "No - Just suggesting the idea"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, examples, or context that would help
      placeholder: |
        Screenshots, links to related discussions, performance metrics, etc.
    validations:
      required: false
